//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceNID
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response", Namespace="http://schemas.datacontract.org/2004/07/Almadar.NID.Data")]
    public partial class response : object
    {
        
        private int responseCodeField;
        
        private ServiceReferenceNID.NationalIdNumberDataStructure responseDataField;
        
        private string responseMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceNID.NationalIdNumberDataStructure responseData
        {
            get
            {
                return this.responseDataField;
            }
            set
            {
                this.responseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NationalIdNumberDataStructure", Namespace="http://schemas.datacontract.org/2004/07/Almadar.NID.Data")]
    public partial class NationalIdNumberDataStructure : object
    {
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string BirthPlaceField;
        
        private string FatherNameField;
        
        private string FistNameField;
        
        private string GrandFatherNameField;
        
        private string NationalIdNumberField;
        
        private System.Nullable<int> PersonIDField;
        
        private string SurNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthPlace
        {
            get
            {
                return this.BirthPlaceField;
            }
            set
            {
                this.BirthPlaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName
        {
            get
            {
                return this.FatherNameField;
            }
            set
            {
                this.FatherNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FistName
        {
            get
            {
                return this.FistNameField;
            }
            set
            {
                this.FistNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrandFatherName
        {
            get
            {
                return this.GrandFatherNameField;
            }
            set
            {
                this.GrandFatherNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalIdNumber
        {
            get
            {
                return this.NationalIdNumberField;
            }
            set
            {
                this.NationalIdNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersonID
        {
            get
            {
                return this.PersonIDField;
            }
            set
            {
                this.PersonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurName
        {
            get
            {
                return this.SurNameField;
            }
            set
            {
                this.SurNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceNID.IimplementationOfNid")]
    public interface IimplementationOfNid
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IimplementationOfNid/SearchIdentityData", ReplyAction="http://tempuri.org/IimplementationOfNid/SearchIdentityDataResponse")]
        System.Threading.Tasks.Task<ServiceReferenceNID.response> SearchIdentityDataAsync(string NID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IimplementationOfNid/AddPhoneNumberToCitizen", ReplyAction="http://tempuri.org/IimplementationOfNid/AddPhoneNumberToCitizenResponse")]
        System.Threading.Tasks.Task<int> AddPhoneNumberToCitizenAsync(string NID, string PhoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IimplementationOfNid/ChangePhoneNumberOwner", ReplyAction="http://tempuri.org/IimplementationOfNid/ChangePhoneNumberOwnerResponse")]
        System.Threading.Tasks.Task<int> ChangePhoneNumberOwnerAsync(string OldOwnerNID, string newOwnerNID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IimplementationOfNidChannel : ServiceReferenceNID.IimplementationOfNid, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class IimplementationOfNidClient : System.ServiceModel.ClientBase<ServiceReferenceNID.IimplementationOfNid>, ServiceReferenceNID.IimplementationOfNid
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IimplementationOfNidClient() : 
                base(IimplementationOfNidClient.GetDefaultBinding(), IimplementationOfNidClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IimplementationOfNid.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IimplementationOfNidClient(EndpointConfiguration endpointConfiguration) : 
                base(IimplementationOfNidClient.GetBindingForEndpoint(endpointConfiguration), IimplementationOfNidClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IimplementationOfNidClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IimplementationOfNidClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IimplementationOfNidClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IimplementationOfNidClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IimplementationOfNidClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceNID.response> SearchIdentityDataAsync(string NID)
        {
            return base.Channel.SearchIdentityDataAsync(NID);
        }
        
        public System.Threading.Tasks.Task<int> AddPhoneNumberToCitizenAsync(string NID, string PhoneNumber)
        {
            return base.Channel.AddPhoneNumberToCitizenAsync(NID, PhoneNumber);
        }
        
        public System.Threading.Tasks.Task<int> ChangePhoneNumberOwnerAsync(string OldOwnerNID, string newOwnerNID)
        {
            return base.Channel.ChangePhoneNumberOwnerAsync(OldOwnerNID, newOwnerNID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IimplementationOfNid))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IimplementationOfNid))
            {
                return new System.ServiceModel.EndpointAddress("http://guj-nidwcf-v02:8080/InternalService.svc/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IimplementationOfNidClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IimplementationOfNid);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IimplementationOfNidClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IimplementationOfNid);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IimplementationOfNid,
        }
    }
}
